/*Populate DataSource*/

BEGIN TRAN
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2000.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2002.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2003.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2005.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2006.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2009.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2010.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2012.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2013.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2014.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2015.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2016.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2018.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2019.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2020.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2021.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2022.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2023.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2026.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2027.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg222.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg223.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg227.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg228.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg229.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg232.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg235.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg238.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg239.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg241.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg246.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg248.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg250.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg251.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg260.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg264.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg266.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2030.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg269.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2031.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2033.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2034.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2035.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2038.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg273.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2039.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2041.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2044.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2045.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2048.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2049.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2053.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2056.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2058.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2059.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2061.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2062.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2063.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2064.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2065.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2071.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2072.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2073.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2074.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2075.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2076.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2079.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2080.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2081.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2086.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2087.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2089.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2090.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2092.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2097.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2100.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2106.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2107.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2108.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2109.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2110.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2111.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2112.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2113.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2114.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2115.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg2116.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg285.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg289.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg291.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg292.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg293.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg296.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg299.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg300.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg301.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg303.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg306.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg309.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg311.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg312.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg318.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg319.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg321.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg325.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg326.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg331.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg335.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg336.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg338.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg339.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg340.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg344.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg354.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg366.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg369.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg373.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg374.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg500.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg501.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg504.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg506.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg511.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg517.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg520.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg526.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg527.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg533.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg535.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg539.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg540.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg544.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg548.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg554.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg557.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg558.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg561.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg564.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg565.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg566.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg569.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg571.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg580.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg581.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg584.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg589.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg591.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg593.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg594.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg596.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg598.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg601.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg603.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg608.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg612.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg615.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg616.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg617.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg626.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg628.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg629.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg630.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg633.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg635.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg636.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg638.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg639.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg641.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg680.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg706.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg725.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg726.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg727.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg730.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg731.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg732.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg733.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg734.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg736.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg737.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg738.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg740.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg741.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg743.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg744.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg768.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg772.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg774.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg775.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg777.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg784.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg786.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg789.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg792.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg793.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg801.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg802.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg803.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg804.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg805.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg815.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg816.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg819.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg820.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg823.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg825.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg827.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg829.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg832.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg833.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg834.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg835.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg839.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg844.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg848.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg849.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg852.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg853.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg854.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg856.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg857.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg858.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg859.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg860.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg865.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg869.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg871.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg873.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg874.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg875.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg876.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg877.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg878.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg879.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg880.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg881.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg882.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg886.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg889.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg890.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg892.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg893.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg894.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg897.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg900.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg903.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg907.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg910.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg911.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg912.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg913.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg914.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg915.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg917.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg918.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg919.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg922.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg923.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg927.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg928.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg929.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg930.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg931.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg932.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg935.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg937.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg939.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg940.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg942.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg945.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg946.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg947.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg952.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg953.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg954.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg955.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg957.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg958.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg959.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg961.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg967.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg970.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg971.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg972.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg973.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg976.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg978.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg979.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg980.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg982.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg984.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg987.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg991.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg999.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1000.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1001.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1003.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1004.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1008.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1009.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1010.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1011.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1012.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1013.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1014.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1018.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1021.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1022.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1024.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1026.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1029.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1032.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1033.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1035.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1036.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1040.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1041.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1045.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1046.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1047.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1050.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1053.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1058.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1059.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1061.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1065.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1067.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1069.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1072.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1075.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1078.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1079.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1081.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1082.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1083.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1086.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1090.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1091.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1092.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1093.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1094.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1095.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1097.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1098.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1101.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1102.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1104.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1105.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1109.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1111.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1114.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1115.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1116.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1118.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1119.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1121.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1122.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1126.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1128.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1130.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1134.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1140.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1141.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1142.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1143.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1144.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1145.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1150.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1151.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1152.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1153.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1154.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1155.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1156.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1157.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1160.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1161.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1162.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1163.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1167.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1168.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1169.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1172.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1177.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1178.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1179.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1180.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1184.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1187.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1204.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1205.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1206.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1207.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1209.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1210.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1215.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1216.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1220.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1222.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1223.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1224.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1225.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1229.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1234.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1235.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1236.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1239.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1242.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1244.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1246.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1248.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1252.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1254.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1256.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1259.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1261.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1263.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1264.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1268.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1269.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1270.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1272.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1274.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1276.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1277.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1281.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1282.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1283.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1284.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1285.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1286.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1287.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1288.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1290.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1291.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1292.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1293.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1294.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1295.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1296.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1297.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1298.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1303.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1305.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1306.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1307.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1308.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1309.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1310.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1311.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1312.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1314.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1315.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1316.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1317.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1318.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1325.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1326.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1327.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1328.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1330.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1331.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1333.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1334.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1337.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1338.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1339.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1341.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1342.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1343.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1344.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1346.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1349.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1351.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1352.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1353.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1354.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1356.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1357.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1358.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1359.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1360.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1361.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1362.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1370.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1374.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1375.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1377.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1378.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1379.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1380.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1381.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1382.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1383.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1384.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1385.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1386.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1389.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1390.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1391.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1393.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1396.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1397.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1405.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1406.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1407.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1408.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1409.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1410.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1411.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1412.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1413.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1415.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1416.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1423.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1424.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1425.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1426.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1427.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1428.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1429.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1430.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1431.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1432.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1434.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1435.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1436.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1439.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1440.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1444.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1446.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1450.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1451.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1453.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1454.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1456.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1457.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1459.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1460.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1461.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1462.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1463.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1464.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1466.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1467.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1469.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1470.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1471.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1473.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1475.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1476.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1478.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1479.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1483.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1488.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1489.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1490.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1493.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1494.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1496.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1497.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1498.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1499.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1500.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1501.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1505.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1507.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1508.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1511.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1512.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1523.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1529.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1530.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1535.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1536.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1540.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1543.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1544.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1546.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1548.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1549.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1551.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1552.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1553.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1554.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1555.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1556.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1558.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1559.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1560.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1562.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1563.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1564.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1566.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1567.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1568.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1569.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1570.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1571.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1572.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1573.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1574.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1575.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1576.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1577.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1578.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1579.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1581.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1583.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1584.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1589.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1590.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1591.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1595.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1599.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1600.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1601.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1602.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1603.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1604.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1605.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1606.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1607.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1608.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1610.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1611.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1612.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1615.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1616.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1617.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1619.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1621.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1622.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1623.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1624.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1625.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1626.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1628.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1630.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1633.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1635.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1637.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1640.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1641.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1642.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1643.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1644.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1646.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1648.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1651.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1652.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1653.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1654.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1656.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1657.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1658.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1666.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1669.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1670.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1672.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1678.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1681.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1682.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1683.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1684.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1686.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1689.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1693.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1694.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1696.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1697.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1700.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1701.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1704.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1705.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1706.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1707.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1709.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1710.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1711.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1718.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1719.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1720.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1723.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1725.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1726.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1730.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1734.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1737.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1738.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1742.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1744.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1746.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1748.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1752.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1753.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1754.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1755.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1756.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1757.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1758.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1759.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1760.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1761.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1762.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1763.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1764.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1765.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1766.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1768.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1769.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1771.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1773.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1775.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1776.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1777.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1778.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1779.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1782.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1784.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1785.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1787.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1789.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1791.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1792.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1794.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1795.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1796.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1799.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1800.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1801.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1803.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1804.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1805.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1806.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1807.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1808.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1810.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1811.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1812.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1815.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1816.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1817.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1818.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1820.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1821.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1822.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1823.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1824.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1825.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1827.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1828.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1829.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1830.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1831.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1832.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1833.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1834.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1835.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1836.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1838.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1839.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1841.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1843.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1844.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1845.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1846.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1848.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1849.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1851.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1852.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1854.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1856.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1858.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1859.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1860.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1862.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1866.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1867.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1868.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1869.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1870.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1871.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1872.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1873.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1874.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1876.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1877.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1878.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1879.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1880.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1882.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1883.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1884.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1888.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1889.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1890.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1891.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1892.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1893.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1895.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1896.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1897.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1898.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1899.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1901.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1902.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1903.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1905.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1906.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1909.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1912.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1913.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1914.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1915.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1916.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1917.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1918.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1919.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1920.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1921.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1922.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1923.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1925.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1926.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1928.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1929.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1931.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1934.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1935.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1936.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1937.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1938.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1941.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1942.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1943.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1944.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1945.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1946.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1948.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1949.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1950.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1951.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1952.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1954.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1955.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1956.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1959.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1961.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1962.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1963.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1964.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1965.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1967.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1968.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1969.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1970.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1971.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1972.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1973.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1975.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1977.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1978.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1979.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1980.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1985.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1986.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1987.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1988.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1989.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1990.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1992.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1993.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1994.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1995.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1996.d.lighthousesolar.com/cgi-bin/egauge-show',1)
INSERT INTO DataSource(URI, SourceNameId)
VALUES ('http://lg1997.d.lighthousesolar.com/cgi-bin/egauge-show',1)

COMMIT

GO
